language: node_js 
node_js: "node" # "node" is latest
install: npm install
script: gatsby build
cache:
  npm: true
  directories:
    - "node_modules"
before_deploy:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - AWS_ACCESS_KEY_ID=$AWS_KEY AWS_SECRET_ACCESS_KEY=$AWS_SECRET aws s3 rm s3://$BUCKET --region=$REGION
deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: "mattschaller.com"
  skip_cleanup: true
  acl: public_read
  local_dir: public
branches:
  only:
    - master