sudo: required
language: node_js 
node_js: "node"
cache:
  directories:
    - "node_modules"
install:
  - sudo pip install awscli
script:
  - npm run build
deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: $BUCKET
  skip_cleanup: true
  local_dir: public
  acl: public_read
  cache_control: 'max-age=21600'
after_success:
branches:
  only:
    - master
before_deploy:
  - aws s3 rm s3://$BUCKET --recursive --region=$REGION
after_deploy:
  - aws configure set preview.cloudfront true
  - test $TRAVIS_BRANCH = "master" && aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"